language: node_js

node_js:
  - '10'

cache:
  npm: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
- npm install
- npm install --save-dev jest
- npm run test

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
